### ISSUE TITLE
ImportError: No module named 'transportNTLM'

### ISSUE THREAD

**Issue by yangtoude** [knockrentals/scrapy-elasticsearch#34] opened 2016-08-17 07:59 UTC
I successfully installed it according to the document [https://pypi.python.org/pypi/ScrapyElasticSearch](url). However when i try

`scrapy crawl myspider`

in the Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32, i get this error:

`File "E:\Python35\lib\site-packages\scrapyelasticsearch\scrapyelasticsearch.py", line 25, in <module>
    from transportNTLM import TransportNTLM
ImportError: No module named 'transportNTLM'`

I checked in the folder and the transportNTLM.py module is there.

**Comment by ThomasRafiki** [comment] 2016-08-30 00:57
I have the same issue here. Please what i do. I have Python 2.7.12 on win64. Please i need a solution ASAP. Thanks

**Comment by jayzeng** [comment] 2016-08-30 01:04
I will take a look tonight

**Comment by ThomasRafiki** [comment] 2016-09-01 04:01
jayzeng, are there previous updates or versions of knockrentals/scrapy-elasticsearch i could try out? If yes, then how do i install it. Thanks

**Comment by jayzeng** [comment] 2016-09-01 04:30
I see what the problem is, fix incoming

**Comment by jayzeng** [comment] 2016-09-01 05:01
@yangtoude @thomaslpetry thanks for reporting the issue and sorry for the delay. There was a typo in the import statement, fixed in https://github.com/knockrentals/scrapy-elasticsearch/pull/37. 

@thomaslpetry you may grab the latest pypi release (https://pypi.python.org/pypi?:action=display&name=ScrapyElasticSearch&version=0.8.3), let me know if you run into other issue.

**Closed by jayzeng** 2016-09-01 05:01 UTC

**Comment by ThomasRafiki** [comment] 2016-09-03 14:16
@jayzeng Thanks for ur effort. I have done exactly what u instructed. installed  ScrapyElasticSearch 0.8.3. 
But now i get this error:
.....
  File "C:\Miniconda2\lib\site-packages\scrapy\utils\misc.py", line 44, in load_
object
    mod = import_module(module)
  File "C:\Miniconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  **File "C:\Miniconda2\lib\site-packages\scrapyelasticsearch\scrapyelasticsearch.
py", line 21, in <module>
    from .transportNTLM import TransportNTLM
  File "C:\Miniconda2\lib\site-packages\scrapyelasticsearch\transportNTLM.py", l
ine 7, in <module>
    from requests_ntlm import HttpNtlmAuth
ImportError: No module named requests_ntlm**

**Comment by jayzeng** [comment] 2016-09-03 17:56
hmm, requests_ntlm doesn't get installed for some reason. Try ```pip install requests_ntlm```

**Comment by ThomasRafiki** [comment] 2016-09-03 19:54
Great! its working now. Thanks
